name: Build Image
on:
  schedule:
    - cron: '0 0 * * * '

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build + Deploy
        run: USER=${{ secrets.DOCKER_HUB_USER }} PASSWORD=${{ secrets.DOCKER_HUB_PASSWORD }} ./build_and_deploy.sh 